version: "3"
services:
    vue-app:
        image: node
        container_name: naffiti-app
        ports:
        - "8080"
        volumes:
        - ./:/opt/app
        command: bash -c "npm run serve"
        working_dir: /opt/app
    nginx: 
        image: nginx:latest
        container_name: proxy_server
        depends_on: 
          - vue-app
        volumes:
          - ./nginx/conf/:/etc/nginx/conf.d/
          - ./nginx/custom:/etc/custom
        ports:
          - 80:80
          - 443:443
    