name: DEPLOY TO UAT SERVER

on:
  push:
    branches:
      - dev

jobs:
  uat-deplay:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Setup Node
      uses: actions/setup-node@master
    
    - name: Installing Project Dependencies
      run: npm ci
      
    - name: Building the Project
      run: npm run build
      
    - name: Deploy to UAT server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: ${{ secrets.SSH_USER }}
        TARGET: "/home/ubuntu/app/"
