name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: deploy (dev)
      uses: appleboy/ssh-action@master
      if: github.ref == 'refs/heads/dev'
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd market-place-front-end
          sudo git pull origin dev
          npm i
          sudo docker-compose down --rmi local
          sudo docker-compose up --build
